### ISSUE TITLE
A6400 Findings

### ISSUE THREAD

**Issue by Funcron** [Staacks/alpharemote#3] opened 2024-11-08 21:49 UTC
PHONE: Samsung S22 Ultra; Android 14.
Camera: A6400; FW Ver. 2.0 w/ Sony 18-105/F4
APP Ver. 0.16
===========================================
- Notification is easily swiped away (some kind of persistence settings needed).
- Notification once swiped, does not return, but can be forced refreshed by adjusting button size setting.
- Notification disappears after waiting for camera to finish writing photo(s), or after a timer delay shutter.
- Camera tab disconnects intermittently if pressing buttons too many times.
- UI positioning of bottom tabs: it's easy to accidentally tap the 'About' tab with the inside of my thumb when reaching across the screen.
- App settings are lacking a delete function for added button options. 'None' persists and will continue to fill list if added, or if multiple options reverted to 'none'.
- 'C1' opens/closes Focus Mode OSD menu on camera, but does nothing else.
- 'Focus button' and 'AF ON' act as a toggle for half-shutter focus in all switch modes (AEL//AF/MF).
- 'App AF ON' does not toggle AF ON, on camera. AF ON on camera persists in ON position regardless of all Switch modes.
- On Manual focus, infinity and Macro focus buttons takes about 45 sec to reach end to end of focus range at 105mm zoom, but only 6 sec on 18mm.
- Too much interaction with the physical camera, pertaining to in app function control, creates a disconnect/reconnect. I.e. Zooming manually.

**Comment by Staacks** [comment] 2024-11-09 01:39
Thanks for the detailed feedback!

> * Notification is easily swiped away (some kind of persistence settings needed).
> * Notification once swiped, does not return, but can be forced refreshed by adjusting button size setting.

That swiping away of notifications is a feature of recent Android versions. They now allow removing notifications even for foreground services, but they still show up in the list of services (if you open the drawer completely and go to the item that gives the number of running services). I have to check if I can make it harder, but I am quite sure that I cannot prevent it like it was possible (or even required) in older Android versions.

> * Notification disappears after waiting for camera to finish writing photo(s), or after a timer delay shutter.

The notification should not appear when the camera finishes some operation. That actually sounds like a the notification was malformed and therefore removed by the system. Do you happen to know how to look into Androids logs ("logcat")?

> * Camera tab disconnects intermittently if pressing buttons too many times.

Is "many times" just the number of presses or also about how fast you press them?

> * UI positioning of bottom tabs: it's easy to accidentally tap the 'About' tab with the inside of my thumb when reaching across the screen.

That's pretty much a standard navigation element. At least I think that an extra menu would be overkill. Do you have a different solution in mind?

> * App settings are lacking a delete function for added button options. 'None' persists and will continue to fill list if added, or if multiple options reverted to 'none'.

So, the swipe to delete option is to subtle :) I have to think of a good alternative.

> * 'C1' opens/closes Focus Mode OSD menu on camera, but does nothing else.

That should be the same as pressing the C1 button on your camera, isn't it? Unfortunately, the Bluetooth interface only allows for sending button presses for these specific button, but not actual functions.

> * 'Focus button' and 'AF ON' act as a toggle for half-shutter focus in all switch modes (AEL//AF/MF).

This is similar to the previous item. They should act like half pressing the shutter and the button inside your AF/AE switch (not sure what this is called). Depending on your settings, the AF ON should typically just hold the current focus, while half-pressing the shutter triggers AF. (Having them behave like toggles was my decision, though as I think it is a bit tricky to hold either of them while also pressing the shutter button.)

> * 'App AF ON' does not toggle AF ON, on camera. AF ON on camera persists in ON position regardless of all Switch modes.

I am not sure that I understand. Are we both referring to the button inside the AF/AE dial?

> * On Manual focus, infinity and Macro focus buttons takes about 45 sec to reach end to end of focus range at 105mm zoom, but only 6 sec on 18mm.

Yes, I noted different behavior for different lenses, too, but I do not see how I could control it. It seems like the speed setting for focus is directly passed on to the lens, which interprets this in whichever way it thinks is best. Could you try different speed options for different lenses? You can set the speed for custom buttons and if you combine that with a fixed hold time, you can test it quite reliably. I am especially curious if min and max speed are interpreted differently as I am not even sure that it has any affect on the power zoom that I tested (and which honored the speed setting for the zoom).

> * Too much interaction with the physical camera, pertaining to in app function control, creates a disconnect/reconnect. I.e. Zooming manually.

That is weird. The zoom state is not reported by the camera via Bluetooth. Is manual zoom a power zoom in this case or mechanical? I will try if I can reproduce this on my camera. Maybe there is more control available than I thought.

**Comment by Staacks** [comment] 2024-11-21 22:48
Some follow-ups:
* Swiping away the notification is a [behavior change of Android 14](https://developer.android.com/about/versions/14/behavior-changes-all#non-dismissable-notifications) and cannot be prevented. I have seen discussions whether this should be reverted, but the app already [declares the notification to be ongoing](https://github.com/Staacks/alpharemote/blob/ac2119c0ceed4fefcc66df27f14d0e4cbe9d186b/app/src/main/java/org/staacks/alpharemote/service/NotificationUI.kt#L229) and the rest is in the hands of Android.
* A visible delete button for custom buttons has been added to the custom button edit dialog in the latest version.

Taking out the things that are (unfortunately) beyond my control, I think that there are two actual issue left:
1. The notification sometimes goes away for you after the camera finishes writing photos or a countdown is completed.
2. You get a disconnect if too much is going on (fast inputs in the app or on the camera).

Version 0.17 also had a bug fix of several possible race conditions, i.e. things that go wrong if the app starts handling things in parallel because something new happens while it isn't finished with the previous thing. Could you check if these two items still are a problem?

**Comment by Staacks** [comment] 2024-12-10 11:03
Since a lot has changed since this version and since there have been several bugfixes that are likely to address these issue, I will close this. Feel free to reopen if the issues persist.

**Closed by Staacks** 2024-12-10 11:03 UTC
